# Deployment
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aladhan-com-cdn
  namespace: aladhan-com
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: aladhan-com-cdn
  template:
    metadata:
      annotations:
        kuma.io/mesh: islamic-network-mesh
      labels:
        app: aladhan-com-cdn
    spec:
      containers:
      - name: aladhan-com-cdn
        image: islamicnetwork/cdn.aladhan.com:$COMMIT_TAG
        livenessProbe:
          httpGet:
            path: /index.txt
            port: 8080
          initialDelaySeconds: 7
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /index.txt
            port: 8080
          initialDelaySeconds: 7
          periodSeconds: 30
          timeoutSeconds: 3
          failureThreshold: 3
        resources:
          requests:
            cpu: "0.1"
            memory: 20Mi
          limits:
            cpu: "0.1"
            memory: 128Mi
        ports:
        - containerPort: 8080
          protocol: TCP

